site_name: Learnapidoc-ru
#site_description: Курс по документированию API. Вольный перевод курса https://idratherbewriting.com/learnapidoc/, составленного Томом Джонсоном, техническим писателем Amazon.
site_author: StarkovDen
site_url: https://starkovden.github.io/
#repo_name: docops-hq/learnapidoc-ru
#repo_url: https://github.com/docops-hq/learnapidoc-ru
nav:
    - О курсе: index.md
    - Обзор курса: course-overview.md
# Configuration
theme: readthedocs
